### ISSUE TITLE
RuntimeError:cuDNN error:CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by sysuzgg** [HRNet/DEKR#23]
when I run the inference_demo.py as README.md, there was a problem "RuntimeError : cuDNN error : CUDNN_STATUS_NOT_INITIALIZED". How to solve the problem?

**Comment by sysuzgg** [comment]
The cuda is 11.0, python==3.6.13, torch==1.8.0, torchvision==0.9.0, numpy==1.19.5, opencv-python==4.5.4.

**Comment by tfederico** [comment]
I solved it by upgrading to torch 1.8.1

**Comment by sysuzgg** [comment]
Thanks very much! I have solved the problem.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HRNet/DEKR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HRNet/DEKR] RuntimeError:cuDNN error:CUDNN_STATUS_NOT_INITIALIZED (Issue #23)





 
I solved it by upgrading to torch 1.8.1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chaowentao** [comment]
@sysuzgg @tfederico hello, I also meet the same question. Please tell me your solution. Thank you very much. =_=

**Comment by sysuzgg** [comment]
我遇到这个问题是由于torch、torchvision和cuda的版本不匹配，torch==0.8.2，torchvision==1.7.1, cuda10.1，其他按照requirement.txt里的要求配置，就这样没报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HRNet/DEKR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HRNet/DEKR] RuntimeError:cuDNN error:CUDNN_STATUS_NOT_INITIALIZED (Issue #23)





 
@sysuzgg @tfederico hello, I also meet the same question. Please tell me your solution. Thank you very much. =_=
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chaowentao** [comment]
@sysuzgg 谢谢啊，我的显卡是2080ti，直接使用conda安装的cuda，cudnn。
```
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch
```
按照上述命令进行安装的，不知道为啥就报错了……

**Comment by sysuzgg** [comment]
我的显卡也是2080ti，看起来你这样是没问题的呢，只是我的cuda是单独安装的，你再多摸索一下，这个报错就是cuda、cudnn和pytorch版本的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HRNet/DEKR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HRNet/DEKR] RuntimeError:cuDNN error:CUDNN_STATUS_NOT_INITIALIZED (Issue #23)





 
@sysuzgg 谢谢啊，我的显卡是2080ti，直接使用conda安装的cuda，cudnn。
 conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch  
按照上述命令进行安装的，不知道为啥就报错了……
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chaowentao** [comment]
@sysuzgg 你说的有道理，那个机器上面没安装cuda，我直接用conda安装的cuda，然后就出现了这个问题。可能我需要先安装好cuda和cudnn，然后再使用pip安装。

**Comment by sysuzgg** [comment]
你对这个模型研究的怎样了呢？我用这个模型测试了一下自己的数据，可视化后，人群中只能检测出2个人的关键点，不知道什么原因，可否指教一下呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HRNet/DEKR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HRNet/DEKR] RuntimeError:cuDNN error:CUDNN_STATUS_NOT_INITIALIZED (Issue #23)





 
@sysuzgg 你说的有道理，那个机器上面没安装cuda，我直接用conda安装的cuda，然后就出现了这个问题。可能我需要先安装好cuda和cudnn，然后再使用pip安装。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
